name: 'CI'

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 2
      - name: Setup Node environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
      - name: Cache NodeJS dependencies
        uses: actions/cache@v4.2.4
        id: nodejs-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('./package-lock.json') }}
      - name: Install NodeJS dependencies
        if: ${{ steps.nodejs-cache.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit
      - name: Run tests
        run: npm run test
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          use_oidc: true
          directory: 'coverage'
          fail_ci_if_error: true
      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          use_oidc: true
          directory: 'build/junit'
          fail_ci_if_error: true

  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
      - name: Setup Node environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
      - name: Cache NodeJS dependencies
        uses: actions/cache@v4.2.4
        id: nodejs-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('./package-lock.json') }}
      - name: Install NodeJS dependencies
        if: ${{ steps.nodejs-cache.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit
      - name: Run build
        run: npm run build
