name: 'CI'

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
      - name: Setup Node environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
      - name: Cache NodeJS dependencies
        uses: actions/cache@v4.2.4
        id: nodejs-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('./package-lock.json') }}
      - name: Install NodeJS dependencies
        if: ${{ steps.nodejs-cache.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit
      - name: Run tests (Mocha)
        run: npm run test
      - name: Run tests (Jest)
        run: npm run test:jest

  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
      - name: Setup Node environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
      - name: Cache NodeJS dependencies
        uses: actions/cache@v4.2.4
        id: nodejs-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('./package-lock.json') }}
      - name: Install NodeJS dependencies
        if: ${{ steps.nodejs-cache.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit
      - name: Run build
        run: npm run build
