name: 'CI'

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # For Codecov uploads
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 2
          persist-credentials: 'false'
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          package-manager-cache: true
      - name: Install NodeJS dependencies
        run: pnpm install --no-runtime --prefer-offline --frozen-lockfile
      - name: Run tests
        run: pnpm run test
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          report_type: 'coverage'
          directory: 'coverage'
          fail_ci_if_error: true
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          report_type: 'test_results'
          directory: 'build/junit'
          fail_ci_if_error: true

  lint:
    name: 'Lint'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 2
          persist-credentials: 'false'
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          package-manager-cache: true
      - name: Install NodeJS dependencies
        run: pnpm install --no-runtime --prefer-offline --frozen-lockfile
      - name: Lint
        run: pnpm run lint

  format:
    name: 'Format'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 2
          persist-credentials: 'false'
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          package-manager-cache: true
      - name: Install NodeJS dependencies
        run: pnpm install --no-runtime --prefer-offline --frozen-lockfile
      - name: Format
        run: pnpm run fmt:check

  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          package-manager-cache: true
      - name: Install NodeJS dependencies
        run: pnpm install --no-runtime --prefer-offline --frozen-lockfile
      - name: Run build
        run: pnpm run build
