name: 'GitHub Actions Security'

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # For advanced security reports
      contents: read # Recommended reads to avoid GraphQL/SAST gaps
      actions: read # Recommended reads to avoid GraphQL/SAST gaps
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: true
          persona: 'pedantic'
          inputs: |
            .github/workflows/

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: GitHub Actions linter
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
