name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: token
        with:
          client-id: ${{ secrets.RELEASE_PLEASE_OSS_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_OSS_BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - name: Release Please
        uses: release-please-oss/release-please-action@main # zizmor: ignore[unpinned-uses]
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
          release-type: node
          # language=json
          config-overrides-json: |
            {
              "changelog-sections": [
                {
                  "type": "feat",
                  "hidden": false,
                  "section": "Features"
                },
                {
                  "type": "feature",
                  "hidden": false,
                  "section": "Features"
                },
                {
                  "type": "fix",
                  "hidden": false,
                  "section": "Bug Fixes"
                },
                {
                  "type": "chore",
                  "hidden": false,
                  "section": "Miscellaneous Chores"
                },
                {
                  "type": "docs",
                  "hidden": false,
                  "section": "Documentation"
                },
                {
                  "type": "refactor",
                  "hidden": false,
                  "section": "Code Refactoring"
                },
                {
                  "type": "deps",
                  "hidden": false,
                  "section": "Dependency updates"
                }
              ]
            }
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.token.outputs.token }}
          persist-credentials: 'true'
      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        env:
          MAJOR: ${{ steps.release.outputs.major }}
          MINOR: ${{ steps.release.outputs.minor }}
          GIT_USER_NAME: ${{ secrets.RELEASE_PLEASE_OSS_BOT_GIT_NAME }}
          GIT_USER_EMAIL: ${{ secrets.RELEASE_PLEASE_OSS_BOT_GIT_EMAIL }}
        # language=bash
        run: |
          git config user.name "${GIT_USER_NAME}"
          git config user.email "${GIT_USER_EMAIL}"
          git tag -d "v${MAJOR}" || true
          git tag -d "v${MAJOR}.${MINOR}" || true
          git push origin ":v${MAJOR}" || true
          git push origin ":v${MAJOR}.${MINOR}" || true
          git tag -a "v${MAJOR}" -m "Release v${MAJOR}"
          git tag -a "v${MAJOR}.${MINOR}" -m "Release v${MAJOR}.${MINOR}"
          git push origin "v${MAJOR}"
          git push origin "v${MAJOR}.${MINOR}"
